---
title: "Full Processing Pipeline Negative and Positive for Final Plots"
output:
  word_document: default
  pdf_document: default
  html_document:
    df_print: paged
---

# Import Everything: 

```{r, warning=FALSE}
library(ggplot2)
library(dplyr)
library(gtools)
library(fANCOVA)
library(pbapply)
library(readxl)
library(data.table)
library(stringr)
library(gt)
library(rlist)
library(purrr)
library(cowplot)
library(scales)
library(tidyverse)
library(ggtext)
library(pdftools)


source("DataExtraction.R")
source("LOESS_Functions.R")
source("getWTdf.R")
source("Comparison_Functions.R")
source("plotFunctions.R")

```

load selected plots
```{r}
# import selected plots
DATA_FOLDER = "D:/R_Analysis/output_files/ASKA/Batch_1"
#setwd(DATA_FOLDER)
filename = file.path(DATA_FOLDER, "teststrains.csv", sep="")
selected_plots <- suppressWarnings(read.csv((filename)))

# convert neg/pos to 1/2 respectively
selected_plots <- selected_plots %>% mutate(Sign=ifelse(Sign=="neg", 1, 2))
```

load the saved all plot data

```{r}
#DATA_FOLDER = "D:/R_Analysis/Data/KEIO/Batch_5"
setwd(DATA_FOLDER)
allplotdata = read.csv(file.path(DATA_FOLDER, 'allplotdata_1.csv', sep=""))
load(file.path(DATA_FOLDER, 'Batch1_data.rda', sep=""))
```

Make the final plots

```{r fig.width=4, fig.height=4, warning=FALSE}
library(ggpubr)
library(ggplot2)
library(purrr)


# y axis title
Y_AXIS_LABEL = "Peak Area (x10^6)"
LABEL_SIZE = 1

# adjust title, size in points (pt)
TITLE_SIZE = "12pt"
COMPOUND_SIZE = "10pt"

# adjust axis text
AXIS_TEXT_COLOR = "black"  
# adjust font size of numbers on the axis
AXIS_TEXT_SIZE = 12

# adjust axis title size
AXIS_X_TITLE_SIZE = 12
AXIS_Y_TITLE_SIZE = 12

# adjust axis line
AXIS_LINE_WIDTH = 1
AXIS_LINE_COLOR = "black"

AXIS_TICK_LENGTH = -3

#serum color
SERUM_LINE_COLOR = "darkgoldenrod2"
#WT color
WT_LINE_COLOR = "darkblue"
#strain color
STRAIN_LINE_COLOR = "red2"


# plot lone width
PLOT_LINE_WIDTH = 0.8
# error bars width
ERROR_BARS_WIDTH = 0.5
# error bars size
ERROR_BARS_SIZE = 0.5

# legend
LEGEND_TEXT_SIZE = 10
LEGEND_KEY_SIZE = 2

# http://www.sthda.com/english/wiki/ggplot2-point-shapes
# adjust the markup types
# 15 - square
# 18 - diamond
# 19 - circle
MARKER_TYPE = 15
# change the marker size
MARKER_SIZE = 2

make_summary_df <- function(x, strain, normdata){
  df <- na.omit(make_compound_df(x, normdata)[,c(2:4)])
  df <- df[df$Strain %in% c("WT", strain, "Ser", "WashGlucose"),]
  s <- df %>% mutate(Area=Area/10^6) %>%
    group_by(Strain, Time)%>%
    summarise(Avarea = mean(Area), stdevArea = sd(Area, na.rm = TRUE), seArea = stdevArea/sqrt(3))
  print("summary")
  print(df)
  return(s) 
}


make_final_plot<- function(pnum, sgn, strain, l, long_name_index){
  if(sgn==1){
    normdata <- neg_data.corrected
  }else{
    normdata <-  pos_data.corrected
  }
  
  print(paste("Sign: ", sgn))
  
  if(sgn==2){
    formula <- gsub(" ","",pos_data$Formula[[pnum-1]])
    compound <- pos_data$Name[[pnum-1]]
    level <- pos_data_levels$level[[pnum-1]]
  }else{
    formula <- gsub(" ","",neg_data$Formula[[pnum-1]])
    compound <- neg_data$Name[[pnum-1]]
    level <- neg_data_levels$level[[pnum-1]]
  }
  
  long_names <- list()
  long_name <- ""
  if(nchar(compound) > 20){
    long_names[length(long_names)+1] <- compound
    long_name <- paste("Compound #", long_name_index," ->",compound)
    compound = paste("Compound #",long_name_index, sep="")
    print(long_name)
    print(pnum)
  }
  
  # create dataframe for plotting the line chart
  df <- make_summary_df(pnum, strains[strain], normdata)
  print(df)
  
  #This level rearrangement is to make sure the colors are consistent.
  target <- c("WashGlucose", "Ser", "WT", strains[strain])
  df$Strain <- factor(df$Strain, levels=target)
  washA <- df[df$Strain=="WashGlucose", 3][[1]]
  name <- names(normdata)[[pnum]]
  df$Time <- as.numeric(as.character(df$Time))
 
  
  # create the title html text
  title = paste("<b><span style = 'font-size:",TITLE_SIZE,"'>",l,".</b></span> <span style ='font-size:",COMPOUND_SIZE,"' >",compound,"(",level,")</span>", sep="")
  
  p <- ggplot(data = df, aes(x=Time, y=Avarea, group=Strain, color=Strain)) +
      geom_line(size=PLOT_LINE_WIDTH) + geom_point(size=MARKER_SIZE, shape=MARKER_TYPE) + 
      geom_errorbar(aes(x = Time, ymin=Avarea-seArea, ymax=Avarea+seArea), width=ERROR_BARS_WIDTH, size=ERROR_BARS_SIZE) +
      scale_color_manual(values=c(SERUM_LINE_COLOR, WT_LINE_COLOR, STRAIN_LINE_COLOR)) + 
      theme_classic() +
      theme(axis.ticks.length = unit(AXIS_TICK_LENGTH, "points")) +
      labs(x = "Time (min)", y=Y_AXIS_LABEL, title=title)+
      theme(plot.title = element_textbox_simple(
      size = 13,
        lineheight = 1,
        padding = margin(5.5, 5.5, 5.5, 5.5),
        margin = margin(0, 0, 5.5, 0),
        fill = "white"
      )) +
      theme(legend.text = element_text(size = LEGEND_TEXT_SIZE), 
            legend.title = element_blank(),
            legend.key.size = unit(LEGEND_KEY_SIZE, 'cm')) +
      theme(legend.position="none") +
      scale_x_continuous(breaks = c(0, 5, 15, 30), labels = c(0, 5, 15, 30))+
      theme(axis.line = element_line(linewidth = AXIS_LINE_WIDTH, color=AXIS_LINE_COLOR)) +
      theme(axis.text.x = element_text(size = AXIS_TEXT_SIZE, colour = AXIS_TEXT_COLOR),
            axis.text.y = element_text(size = AXIS_TEXT_SIZE, colour = AXIS_TEXT_COLOR),
            axis.title.y=element_text(size=AXIS_Y_TITLE_SIZE, face="bold"),
            axis.title.x=element_text(size=AXIS_X_TITLE_SIZE, face="bold"),
            )
  return (list(p, long_name))
}




```

Extract Priority and Non Priority plots

```{r}
priority = selected_plots[1, ] %>% filter(Priority=="Yes")
non_priority = selected_plots %>% filter(Priority!="Yes")
```

# Produce the combined figures for priority plots

```{r}

ss <- c(rep(0, nrow(priority)))
labels <- LETTERS[seq( from = 1, to = nrow(priority))]

ss <- c()
long_names <- c()

for(row in 1:nrow(priority)){
  stn<-priority[row, "Strain"]
  plt<-priority[row, "Plot"]
  sgn<-priority[row, "Sign"]
  
  CompoundcolumnNumber <- (allplotdata %>% filter(Strain==stn) %>% filter(Sign==sgn) %>% filter(Plt==plt))$CompoundNumber
  print(CompoundcolumnNumber)
  results <- make_final_plot(CompoundcolumnNumber, sgn, stn, labels[[row]], length(long_names)+1)
  ss[row]<- results[1]
  long_name<-results[2]
  if(long_name != ""){
    long_names[length(long_names)+1] <- long_name
  }
}


# number of plots on a page
MAX_PLOTS <- 4
# For 4 panels use (6, 6)
# For 2 panels use (6, 3)
# For 1 panel use (4,3 )
PAGE_WIDTH <- 6 # inches
PAGE_HEIGHT <- 6 # inches

MAX_PLOTS <- min(4, MAX_PLOTS)

if(MAX_PLOTS == 1){
  NUM_COLUMNS = 1
  NUM_ROWS = 1
}
if(MAX_PLOTS == 2){
  NUM_COLUMNS = 2
  NUM_ROWS = 1
}
if(MAX_PLOTS == 4){
  NUM_COLUMNS = 2
  NUM_ROWS = 2
}

page <- 1
paths <- c()
for(i in seq(1, nrow(priority), MAX_PLOTS)){
  plts <- c()
  for(j in 0: MAX_PLOTS-1){
    idx <- i + j
    if(idx <= nrow(priority)){
      plts[j+1] <- ss[idx]
    }
  }
  filename <- paste("output", page, ".pdf", sep="")
  print(filename)
  plot_grid(plotlist = plts, ncol=NUM_COLUMNS, nrow=NUM_ROWS, scale=0.95)
  legend=get_legend(plts[1])
  ggsave(filename, width=PAGE_WIDTH, height=PAGE_HEIGHT, units = "in")
  paths[length(paths)+1] <- filename
  page <- page + 1
}

pdf_combine(input = paths,
            output = paste(DATA_FOLDER, "/PRIORITY_BATCH_", BATCH, ".pdf", sep=""))


# clean intermediate files generated
for(filename in paths){
  unlink(filename)
}

print(long_names)
```

# Produce the combined figures for non priority plots

```{r}

ss <- c(rep(0, nrow(non_priority)))
labels <- LETTERS[seq( from = 1, to = nrow(selected_plots))]

ss <- c()
long_names <- c()

for(row in 1:nrow(non_priority)){
  stn<-non_priority[row, "Strain"]
  plt<-non_priority[row, "Plot"]
  sgn<-non_priority[row, "Sign"]
  
  CompoundcolumnNumber <- (allplotdata %>% filter(Strain==stn) %>% filter(Sign==sgn) %>% filter(Plt==plt))$CompoundNumber
  print(CompoundcolumnNumber)
  results <- make_final_plot(CompoundcolumnNumber, sgn, stn, labels[[row]], length(long_names)+1)
  ss[row]<- results[1]
  long_name<-results[2]
  if(long_name != ""){
    long_names[length(long_names)+1] <- long_name
  }
}

# number of plots on a page
MAX_PLOTS <- 4
PAGE_WIDTH <- 6 # inches
PAGE_HEIGHT <- 6 # inches

page <- 1
paths <- c()
for(i in seq(1, nrow(non_priority), MAX_PLOTS)){
  plts <- c()
  for(j in 0: MAX_PLOTS-1){
    idx <- i + j
    if(idx <= nrow(non_priority)){
      plts[j+1] <- ss[idx]
    }
  }
  filename <- paste("output", page, ".pdf", sep="")
  print(filename)
  plot_grid(plotlist = plts, ncol=2, nrow=MAX_PLOTS/2, scale=0.95)
  legend=get_legend(plts[1])
  ggsave(filename, width=PAGE_WIDTH, height=PAGE_HEIGHT, units = "in")
  paths[length(paths)+1] <- filename
  page <- page + 1
}

pdf_combine(input = paths,
            output = paste(DATA_FOLDER,"/NONPRIORITY_BATCH_", BATCH, ".pdf", sep=""))

# clean intermediate files generated
for(filename in paths){
  unlink(filename)
}

print(long_names)

```

