---
title: "Stage1 HTML Generator"
output: html_document
date: "2023-07-20"
params:
  all_plots_file: ""
  neg_data: NA
  neg_data.corrected: NA
  neg_data_levels: NA
  wt_fits_sigs_neg: NA
  pos_data: NA
  pos_data.corrected: NA
  pos_data_levels: NA
  wt_fits_sigs_pos: NA
  strains: c()
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning=FALSE}
library(ggplot2)
library(dplyr)
library(gtools)
library(fANCOVA)
library(pbapply)
library(readxl)
library(data.table)
library(stringr)
library(gt)
library(rlist)
library(purrr)
library(cowplot)
library(scales)

source("DataExtraction.R")
source("LOESS_Functions.R")
source("getWTdf.R")
source("Comparison_Functions.R")
source("plotFunctions.R")
```

# Load saved data frames

```{r}
#load(params$filename)
```

# check if neg or pos data is to be plotted
```{r}
POS_AVAILABLE = FALSE
NEG_AVAILABLE = FALSE
if(length(params$neg_data) > 1){
  NEG_AVAILABLE = TRUE
}
if(length(params$pos_data) > 1){
  POS_AVAILABLE = TRUE
}
```

# Strains

```{r}
print(strains)
```

# Generate plots:

```{r, include=FALSE}
panel_label_font_size <- 30
plot_line_width <- 1
wt_line_color <- "darkblue"
serum_line_color <- "darkgoldenrod2"
strain_line_color <- "red2"
y_axis_scale <- 10^6
axis_labels_font_size <- 15
plot_dot_width <- 5

if(NEG_AVAILABLE == TRUE){
  plots_neg_lines<- lapply(strains, plot_strain, normdata=params$neg_data.corrected,  sig_data = params$wt_fits_sigs_neg)
}

if(POS_AVAILABLE == TRUE){
plots_pos_lines <- lapply(strains, plot_strain, normdata=params$pos_data.corrected,  sig_data = params$wt_fits_sigs_pos)
}
```

# Filter for Detected Compounds and with Level <= 3

```{r, warning=FALSE}

isDetected <- function(x) return (df[x[[3]]-1, 3] <=3 & !str_detect(x[[1]][[1]], "Var."))
filter_compounds <- function(x){
  return  (Filter(isDetected, x))
}

if(NEG_AVAILABLE == TRUE){
  df <- params$neg_data_levels
  plots_neg_lines_filtered <- lapply(plots_neg_lines, filter_compounds)
}


if(POS_AVAILABLE == TRUE){
  df <- params$pos_data_levels
  plots_pos_lines_filtered <- lapply(plots_pos_lines, filter_compounds)
}
```

# Add the levels to the plots

```{r}
addLevel2<-function(X, df){
  level <- df[X[[3]]-1, 3]
  original_title <- levelled_data[X[[3]]-1, 2]
  title = sprintf("%s (%s)", if_else(original_title=="", X[[1]], original_title), level)
  title <- str_wrap(stringi::stri_enc_toutf8(title, is_unknown_8bit = FALSE), width=30)
  X[[2]]$labels$title <- title
  return (X)
}

addLevel <- function(x, df){
  return (map(x, addLevel2, df))
}

if(NEG_AVAILABLE == TRUE){
 levelled_data <- neg_data_levels
 plots_neg_lines_filtered_level <- lapply(plots_neg_lines_filtered, addLevel, params$neg_data_levels)
}

if(POS_AVAILABLE == TRUE){
  levelled_data <- pos_data_levels
  plots_pos_lines_filtered_level <- lapply(plots_pos_lines_filtered, addLevel, params$pos_data_levels)
}
```

Save the combined data frame

```{r}

all_plots <- list()

for(i in c(1:length(strains))){
  inner <- list()
  if(NEG_AVAILABLE==TRUE){
    inner <- append(inner, list(plots_neg_lines_filtered_level[[i]] ))
  }
  if(POS_AVAILABLE==TRUE){
    inner <- append(inner, list(plots_pos_lines_filtered_level[[i]] ))
  }
  all_plots <- append(all_plots, list(inner))
}

# get strains
stn <- c()
# get signs
sign <- c()
# get plot num
plot_num <- c()
# formula
formulas <- c()
# level
levels <- c()
# name
compounds <- c()

# compound number in the pos or negative original data frames
compound_numbers <- c()

# if both negative and positive
if(POS_AVAILABLE == TRUE && NEG_AVAILABLE == TRUE){
for(i in c(1:length(strains))){
  for(j in c(1:2)){
    for(k in c(1:length(all_plots[[i]][[j]]))){
      stn[length(stn)+1] <- i
      sign[length(sign)+1] <- j
      plot_num[length(plot_num)+1] <- k
      compound <- all_plots[[i]][[j]][[k]][[1]]
      compound_num <- all_plots[[i]][[j]][[k]][[3]]
      compounds[length(compounds)+1] <- compound
      compound_numbers[length(compound_numbers)+1] <- compound_num
      if(j == 1){
        formula <- neg_data_levels$Formula[compound_num-1]
        level <- neg_data_levels$level[compound_num-1]
      }
      if(j == 2){
        formula <- pos_data_levels$Formula[compound_num-1]
        level <- pos_data_levels$level[compound_num-1]
      }
      formulas[length(formulas)+1] <- formula
      levels[length(levels)+1] <- level
    }
  }
}
}else{
  # For negative or positive only
  for(i in c(1:length(strains))){
      print(length(all_plots[[i]]))
      for(k in c(1:length(all_plots[[i]][[1]]))){
        stn <- append(stn, i)
        plot_num <- append(plot_num, k)
        compound <- all_plots[[i]][[1]][[k]][[1]]
        compound_num <- all_plots[[i]][[1]][[k]][[3]]
        # # print(compound_num)
        # # knitr::knit_exit()
        compounds[length(compounds)+1] <- compound
        compound_numbers[length(compound_numbers)+1] <- compound_num
        if(NEG_AVAILABLE==TRUE){
          formula <- neg_data_levels$Formula[compound_num-1]
          level <- neg_data_levels$level[compound_num-1]
          sign <- append(sign, 1)
        }
        if(POS_AVAILABLE==TRUE){
          formula <- pos_data_levels$Formula[compound_num-1]
          level <- pos_data_levels$level[compound_num-1]
          sign <- append(sign, 2)
        }
        formulas[length(formulas)+1] <- formula
        levels[length(levels)+1] <- level
      }
  }
}

alldata_df <- data.frame(Strain=stn, Sign=sign, Plt=plot_num, Formula=formulas, Level=levels, Name=compounds, CompoundNumber=compound_numbers)
write.csv(alldata_df, params$all_plots_file)
```


# Strain 1 - Neg
```{r}
if(NEG_AVAILABLE==TRUE && length(strains) >= 1){
  plots_neg_lines_filtered_level[[1]]
}
```

# Strain 1 - Pos
```{r}
if(POS_AVAILABLE==TRUE && length(strains) >= 1){
  plots_pos_lines_filtered_level[[1]]
}
```

# Strain 2 - Neg
```{r}
if(NEG_AVAILABLE==TRUE && length(strains) >= 2){
  plots_neg_lines_filtered_level[[2]]
}
```

# Strain 2 - Pos
```{r}
if(POS_AVAILABLE==TRUE && length(strains) >= 2){
  plots_pos_lines_filtered_level[[2]]
}
```

# Strain 3 - Neg
```{r}
if(NEG_AVAILABLE==TRUE && length(strains) >= 3){
  plots_neg_lines_filtered_level[[3]]
}
```

# Strain 3 - Pos
```{r}
if(POS_AVAILABLE==TRUE && length(strains) >= 3){
  plots_pos_lines_filtered_level[[3]]
}
```

# Strain 4 - Neg
```{r}
if(NEG_AVAILABLE==TRUE && length(strains) >= 4){
  plots_neg_lines_filtered_level[[4]]
}
```

# Strain 4 - Pos
```{r}
if(POS_AVAILABLE==TRUE && length(strains) >= 4){
  plots_pos_lines_filtered_level[[4]]
}
```

# Strain 5 - Neg
```{r}
if(NEG_AVAILABLE==TRUE && length(strains) >= 5){
  plots_neg_lines_filtered_level[[5]]
}
```

# Strain 5 - Pos
```{r}
if(POS_AVAILABLE==TRUE && length(strains) >= 5){
  plots_pos_lines_filtered_level[[5]]
}
```


# Strain 6 - Neg
```{r}
if(NEG_AVAILABLE==TRUE && length(strains) >= 6){
  plots_neg_lines_filtered_level[[6]]
}
```

# Strain 6 - Pos
```{r}
if(POS_AVAILABLE==TRUE && length(strains) >= 6){
  plots_pos_lines_filtered_level[[6]]
}
```